# Created with YamlCreate.ps1 v2.2.1 using InputObject 🤖 $debug=QUSU.CRLF.7-2-10
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: Balena.Etcher
PackageVersion: 1.18.4
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
FileExtensions:
- bz2
- dmg
- dsk
- etch
- gz
- hddimg
- img
- iso
- raw
- xz
- zip
ReleaseDate: 2023-03-02
Installers:
- Architecture: neutral
  InstallerUrl: https://github.com/balena-io/etcher/releases/download/v1.18.4/balenaEtcher-Setup-1.18.4.exe
  InstallerSha256: EAEC03357A06C213F4A966F44E2F0FA5B6F19CA4F5147FE9BD61B27431E0BA5B
ManifestType: installer
ManifestVersion: 1.2.0
