# Created with WinGet Releaser v2 using Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Balena.Etcher
PackageVersion: 1.19.19
Platform:
- Windows.Desktop
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
FileExtensions:
- bz2
- dmg
- dsk
- etch
- gz
- hddimg
- img
- iso
- raw
- xz
- zip
ReleaseDate: 2024-05-28
Installers:
- Architecture: neutral
  InstallerUrl: https://github.com/balena-io/etcher/releases/download/v1.19.19/balenaEtcher-1.19.19.Setup.exe
  InstallerSha256: 275DBE182E9F946A1C67AC83F0D00F62412A3BDB50BC6DBEDCFEF25F1603C982
ManifestType: installer
ManifestVersion: 1.5.0
