# Created with WinGet Releaser v2 using Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Balena.Etcher
PackageVersion: 1.19.21
Platform:
- Windows.Desktop
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
FileExtensions:
- bz2
- dmg
- dsk
- etch
- gz
- hddimg
- img
- iso
- raw
- xz
- zip
ReleaseDate: 2024-05-30
Installers:
- Architecture: neutral
  InstallerUrl: https://github.com/balena-io/etcher/releases/download/v1.19.21/balenaEtcher-1.19.21.Setup.exe
  InstallerSha256: D65FCF62F303FE02117095B2F8C1FD00D873CBE98F4037C62B6D65A3281A66FF
ManifestType: installer
ManifestVersion: 1.5.0
